# Generated by Django 4.0.1 on 2022-02-10 00:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(default='', max_length=8, unique=True)),
                ('complete', models.BooleanField(default=False)),
                ('crash_reward', models.IntegerField(default=-100)),
                ('land_reward', models.IntegerField(default=100)),
                ('first_leg_reward', models.IntegerField(default=10)),
                ('second_leg_reward', models.IntegerField(default=10)),
                ('main_engine_reward', models.FloatField(default=0.3)),
                ('side_engine_reward', models.FloatField(default=0.03)),
                ('algorithm', models.CharField(default='DQN', max_length=5)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
